version: '3.3'
services:
    tor:
        container_name: tor-relay
        environment:
            - RELAY_TYPE=exit
            - TOR_ORPort=9001
            - TOR_DirPort=80
            - TOR_Nickname=noconname
            - TOR_ContactInfo="NcN tor@noconname.org"
            - TOR_RelayBandwidthRate="100 KBytes"
            - TOR_RelayBandwidthBurst="200 KBytes"
            - TOR_DirPortFrontPage="/data/index.html"
            - TZ=Europe/London
            - PUID=$$(id -u)
            - PGID=$$(id -g)
        volumes:
            - '$PWD/tor/data:/data:Z'
        ports:
            - '9001:9001'
            - '80:80'
        entrypoint:
            - /entrypoint.sh
        restart: always
        image: 'noconname/tor:1.0'
